service:
  name: dojo-serverless-backend

package:
  exclude:
    - .git/**
    - .gitignore

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  profile: dojo-serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt': [DojoServerlessTable, Arn]
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  hello:
    handler: hello.main
    events:
      - http:
          method: get
          path: hello
          cors: true
  getVirus:
    handler: src/handlers/virus/get.main
    events:
      - http:
          method: get
          path: virus
          cors: true

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamoDB.yml)}
